version: '3'

services:
  db:
    image: postgres:15
    container_name: intern_postgres
    ports:
      - "15432:5432"
    volumes:
      - '${PWD}/dev/db/data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Ho_Chi_Minh
  minio:
    image: 'minio/minio:latest'
    container_name: intern_minio

    ports:
      - '19001:9001'
      - '19000:9000'
    volumes:
      - "./dev/mnt/minio/data:/data"

    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server /data --console-address ":9001"
  adminer:
    image: adminer
    links:
      - db:db
    ports:
      - 8080:8080


